
include("abstractaxis.jl")
include("axisindices.jl")

include("axis.jl")
include("simpleaxis.jl")
include("reindex.jl")
include("resize.jl")
include("combine.jl")
include("append.jl")
include("cat_axes.jl")
include("drop_axes.jl")
include("matmul_axes.jl")
include("permute_axes.jl")
include("reduce_axes.jl")
include("getindex.jl")
include("promotion.jl")
include("reshape_axes.jl")
